id:
  right: '00C33080959' # 原来的右相机编号'00C33080959' '2BDF34963204'
  new_cam: '2BDF34963204' # 新的右相机编号


param:
  Width: 4024 # 1280
  Height: 3036 # 640
  OffsetY: 0 # 384
  ExposureTime: 25000.0 # 64000. .100000. 33000室内 # 增益呢23
  GammaEnable: True # True False4
  Gamma: 0.7 # 0 0.7
  Gain: 22.0 #
  BalanceWhiteAuto: 'Off'
  BalanceRatioR: 1904
  BalanceRatioG: 1024
  BalanceRatioB: 1723
  show_width: 1920
  show_height: 1080
  pyr_times: 2 # 金字塔层数






