path:
  stage_one_path: "/home/nvidia/RadarWorkspace/code/Radar_Develop/weights/train/stage_one/weights/best.pt" # /home/nvidia/RadarWorkspace/code/Radar_Develop/weights/train/stage_one/weights/best_openvino_model
  stage_two_path: "../weights/train/stage_two/weights/best.pt"
  tracker_path: "../configs/bytetrack.yaml"

params:
  labels: ["B1", "B2", "B3", "B4", "B5", "B7", "R1", "R2", "R3", "R4", "R5", "R7"]
  stage_one_conf: 0.1
  stage_two_conf: 0.5
  life_time: 90 # 生命周期