debug: False


ctrl:
  MODE: 'video'  # 'camera'
  DETECT: True
  RECORDING: False
  GUI: False
  ANCHOR: True

  SENDING: True
  RECEIVING: False

  CALIB: False
  SAVE_CSV: False
  SAVE_IMG: False

  CHESSBOARD: False

video:
  bin_video_root: './video'
  bin_video_left: './video/video1/raw_left.mp4'
  bin_video_right: './video/video1/raw_right.mp4'

weights:
  yolov8: 'G:\LangYa\Radar\模型\detect_all\暑假最后\0801_sumup_80.pt'

portx: 'COM7'